### ISSUE TITLE
Platform exception - Android

### ISSUE THREAD

**Issue by JayPerfetto** [LuisThein/platform_maps_flutter#10]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'apple_maps_flutter'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.34, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.0)
[✓] VS Code (version 1.24.1)
[✓] Connected device (4 available)

• No issues found!

**Comment by JayPerfetto** [comment]
may be related to https://github.com/flutter/flutter/issues/44092

**Comment by JayPerfetto** [comment]
This was my own fault - it was an inelegent failure of having bad AndroidManifest.xml syntax for my permissions. the permissions need to go *after* the closing <application> tag.

**Comment by Akshay-akkay** [comment]
Can you explain in detail how you solved it, please?
