### ISSUE TITLE
Custom marker icon placement point

### ISSUE THREAD

**Issue by fbazbo** [LuisThein/platform_maps_flutter#16]
It seems like the marker icon is always placed by the center if you use a custom marker icon.  I know there's a way to control the relative placement point for both Google maps API and IOS, so can we get that exposed via this API?

**Comment by LuisThein** [comment]
I will look into it 👍

**Comment by fbazbo** [comment]
Also, it seems that for Google Maps the custom marker is placed by the center-bottom, while IOS places by the exact center. And the same scaling factor for both map types makes the Google marker significantly larger than the equivalent on the IOS map

**Comment by LuisThein** [comment]
I fixed the placement of the markers to be the same. I'm looking into how to make the exact placement point customizable.

**Comment by fbazbo** [comment]
Is the placement point still at the center? This is different then the default markers, which seem to place by the bottom-center.

**Comment by JoeCiou** [comment]
@LuisThein  The placement point seems can be customized already by the property "anchor" on Apple's Annotation or Google's Marker, could you open it from Marker on the project?
