### ISSUE TITLE
Programmatically open an infoWindow

### ISSUE THREAD

**Issue by fbazbo** [LuisThein/platform_maps_flutter#17]
Is there a programmatic way to open the infoWindow? I'd like to have it open when the view is first displayed without having to tap on the icon.

**Comment by OmarYehiaDev** [comment]
in `google_maps_flutter` it's done like this 
```
GoogleMap(
  onMapCreated = (controller) {
    controller.showMarkerInfoWindow(markerId);
  }
),
```
And since this package combines `google_maps_flutter` and `apple_maps_flutter` I think you'll find it in the given `controller` from the `onMapCreated` in this package

**Comment by LuisThein** [comment]
Unfortunately this functionallity ist currently not implemented in `apple_maps_flutter` and therefore unavailable in this package. 
I'm actually reworking the Implementation of the `infoWindow` for the `apple_maps_flutter` package and will look into adding this feature.

**Comment by LuisThein** [comment]
This feature will be included in the next release of the apple_maps_flutter package, which will be released soon.
