### ISSUE TITLE
Search Bar not available

### ISSUE THREAD

**Issue by MukundPradhan** [LuisThein/platform_maps_flutter#20]
Hi Dear,
Can we add a search bar here for searching the locations

**Comment by fbazbo** [comment]
@MukundPradhan, you should be able to add that yourself.  I have several additional widgets stacked on top of the map itself that invoke map camera or display commands

**Comment by LuisThein** [comment]
@MukundPradhan This will not be a feature of this plugin. As @fbazbo correctly said, you should be able to implement such behavior with the given api.
