### ISSUE TITLE
Problem with user location

### ISSUE THREAD

**Issue by Marloncheg182** [LuisThein/platform_maps_flutter#21]
I'm using Apple maps from Platform maps package. Location permissions granted to always allow. myLocationEnabled set to true, but there is no user marker on maps. Only when i added myLocationButtonEnabled: true , i see user area by clicking on user location button. Strange behaviour, but i saw this marker only once after update to latest version.

**Comment by LuisThein** [comment]
Please let me know if you still experience this issue.

**Comment by undreeyyy** [comment]
@LuisThein I am also experiencing this.
