### ISSUE TITLE
Scaling custom marker icon via BitmapDescriptor ImageConfiguration argument  doesn't seem to work for android

### ISSUE THREAD

**Issue by fbazbo** [LuisThein/platform_maps_flutter#22]
This code works fine for IOS and the icon gets scaled to a size I'm happy with for my marker assets (png at 177x240px):

```
Future<BitmapDescriptor> getAssetImage(String path, BuildContext context) {
      double dpr = MediaQuery.of(context).devicePixelRatio;
      ImageConfiguration config = ImageConfiguration(devicePixelRatio: dpr*2.0,);
      return BitmapDescriptor.fromAssetImage(config, path);
}
```

For Android, no matter what I pass for the devicePixelRatio, I always get the same size marker icon.

Note, that this might be a bug in the google map implementation since there seem to be similar issues - https://github.com/flutter/flutter/issues/24865

Also, there are some alternative suggestions to size a marker via stackoverflow, but your version of BitmapDescriptor does not implement the fromBytes static method.

**Comment by LuisThein** [comment]
Hey, actually I just discovered that I implemented the icon scaling wrong in apple_maps_flutter. The way it should work is by specifying icon assets for different scales like so:

```
.../my_icon.png
.../2.0x/my_icon.png
.../3.0x/my_icon.png
```

See: https://flutter.dev/docs/development/ui/assets-and-images#declaring-resolution-aware-image-assets

This way you can specify your icon size through the `devicePixelRatio`.
I'm almost finished fixing this and also adding the ability to add custom Icons through the `BitmapDescriptor.fromBytes` method, which will give you additional options to scale your icons as needed.
