### ISSUE TITLE
Implement CameraUpdate.newLatLngBounds

### ISSUE THREAD

**Issue by teryaev** [LuisThein/platform_maps_flutter#27]
Please add support for CameraUpdate.newLatLngBounds. This seems to be already available in flutter/google-maps: https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/example/lib/move_camera.dart#L84-L91. Not sure about the apple maps part though

**Comment by 1AhmedYasser** [comment]
+1
