### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by jonbhanson** [LuisThein/platform_maps_flutter#30]
Thanks for the great package!

Do you plan to make a null safe update of the package?

**Comment by jonbhanson** [comment]
@LuisThein would a PR be helpful for this?  Love the package!

**Comment by bmennear** [comment]
Excellent plugin, would be great to get null safety committed.

**Comment by LuisThein** [comment]
Thanks to the PR from @jonbhanson Null Safety is now implemented!

**Comment by jonbhanson** [comment]
👍🏻 Glad to see the package staying up to date!
