### ISSUE TITLE
setMapStyle?

### ISSUE THREAD

**Issue by mikeKane** [LuisThein/platform_maps_flutter#41]
Does this package support Google Map styling? I need to force it to dark maps and I see 

```
GoogleMapController mapController;
GoogleMap(
  onMapCreated: (GoogleMapController controller) {
    mapController = controller;
    mapController.setMapStyle(_mapStyle);
  }
);
```

I don't see how to do it in this package, is it possible?

**Comment by mikeKane** [comment]
You can! For anyone who needs help 

```onMapCreated: (controller) {
          controller.googleController?.setMapStyle(_mapStyle);
```

**Comment by shinobi018** [comment]
This seems to be deprecated.

- Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision 761747bfc5 (6 weeks ago) • 2024-06-05 22:15:13 +0200
- Engine • revision edd8546116
- Tools • Dart 3.4.3 • DevTools 2.34.3

- platform_maps_flutter: ^1.0.2

```
'setMapStyle' is deprecated and shouldn't be used. Use GoogleMap.style instead.
Try replacing the use of the deprecated member with the replacement.
```

but `style` isn't defined for `PlatformMap` widget. Essentially, is there no way to change the map style on Google Maps? (it works fine on iOS using the default Apple Maps)
