### ISSUE TITLE
Mac OS Desktop Support

### ISSUE THREAD

**Issue by JayPerfetto** [LuisThein/platform_maps_flutter#9]
<img width="804" alt="Screen Shot 2020-05-14 at 11 09 34 AM" src="https://user-images.githubusercontent.com/34031697/81951827-a52c3f80-95d3-11ea-96b9-36eacc0cab87.png">
On MacOS I see a "Platform not yet implemented" message - is there any timeframe for Mac OS Desktop support for flutter which is quickly becoming more richly supported by the flutter team?

Thank you!

**Comment by LuisThein** [comment]
The progress of this issue will be tracked in the issue [#3](https://github.com/LuisThein/apple_maps_flutter/issues/3) in the apple_maps_flutter repository.
